---

- hosts: all
  become: true
  tasks:

  - name: apache 2 install and update cache
    package: 
      name: 
        - httpd
        - php
      update_cache: yes
      state: latest
    when: ansible_distribution == "Amazon"
